### PR TITLE
Updated class names to use bootstrap classes

### PR DESCRIPTION
**Pull request by christohill**
Updated class names to use bootstrap classes. Keeps same style as other CMS alerts

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @christohill 

Sorry for the late reply. I missed this one. 

I seem to miss a bit context. Without having it checked: Wouldn't this break the alerts? 

Cheers,
Peter

**Comment by christohill** [comment]
hey @spekulatius 

No problem. It doesn't break the alerts, just changes the style to use the built in Bootstrap alerts to keep them consistent with other alerts in the admin.

https://getbootstrap.com/docs/4.5/components/alerts/

**Comment by spekulatius** [comment]
Ah, okay. I got to check it out - haven't done much on this recently. I'll check it out shortly

**Comment by spekulatius** [comment]
Looks good to me! Thanks for submitting the PR @christohill!

**Pull request merged**
