### PR TITLE
Silverstripe 5 support

### PR DESCRIPTION
**Pull request by elliot-sawyer**
Checked a couple of NoticeMessage and WarningMessage fields and seems OK to use

### CODE REVIEW

**Comment by elliot-sawyer** [comment]
Any hopes we can merge this soon?

**Comment by spekulatius** [comment]
Hey @elliot-sawyer,

sorry for the delay! I assume the messages still work as expected, right?

Peter

**Comment by elliot-sawyer** [comment]
I've got a handful of SS5 sites using it and haven't encountered any issues

**Comment by spekulatius** [comment]
Awesome, I'll merge it and release a new new version shortly.

**Pull request merged**
